### ISSUE TITLE
Affiliation mapping for CaltechDATA

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/feeds.library.caltech.edu#1]
Need to figure out how to index orcids in the same order as authors.  Need to check that the identifier type is ORCID

**Comment by rsdoiel** [comment]
Reworking affiliation and groups.  I am generating group pages and where the affiliation in DATA and AUTHORS match you should see articles, publications and data but I have a few more bugs to workout.

+ Some DATA only groups show up with empty pages
+ Some non DATA groups have links to an empty DATA page

I think these are a result of how I was handling a list of keys to generate a the JSON feed.  Also I need to normalize (in the output templates) handling display of DATA Schema versus AUTHORS Schema.

**Comment by rsdoiel** [comment]
Closing this was it is related to search and search was dropped when I rolled out v0.0.3.
