### ISSUE TITLE
Newman-D-K's orcid driven feed is missing records compared to CaltechAUTHORS page

### ISSUE THREAD

**Issue by rsdoiel** [caltechlibrary/feeds.library.caltech.edu#10]
EPrints URL: https://authors.library.caltech.edu/view/person-az/Newman-D-K.html
Feeds URL: https://feeds.library.caltech.edu/person/0000-0003-1647-1918/

**Comment by tmorrell** [comment]
Additional example:

No ORCID: https://feeds.library.caltech.edu/api/?fields=*&q=%22Noise+and+control+decoupling+of+Advanced+LIGO+suspensions%22%0D%0A&highlight=true&sort=-sort_date&start=0&size=100&fmt=json&submit=Go

Authors record with ORCID: https://authors.library.caltech.edu/54451/
https://authors.library.caltech.edu/rest/eprint/54451.xml

ORCID present in feeds: https://feeds.library.caltech.edu/api/?fields=*&q=orcid%3A+%220000-0002-5731-5076%22%0D%0A%0D%0A&highlight=true&sort=-sort_date&start=0&size=100&fmt=json&submit=Go

Author record: https://authors.library.caltech.edu/rest/eprint/45768.xml

**Comment by rsdoiel** [comment]
In test I have 156 items, in EPrints I have 158, looks like either a record is missing an ORCID or more likely my development environment is not as up-to-date as production for the entire Authors' collection. Closing this issue as I think this is fixed.
