### ISSUE TITLE
Host zip files of raw dataset collection

### ISSUE THREAD

**Issue by rsdoiel** [caltechlibrary/feeds.library.caltech.edu#12]
It would be convenient to be able to download a zip file of our various dataset collections (e.g. CaltechAUTHORS, CaltechTHESIS, CaltechDATA) for analysis or data reuse. Some of the data would need to be sanitized first (e.g. internal comments removed, email addresses if any removed). 

If our build process moves from directly storing our collections in S3 to mirroring our dataset collections to S3 then we could easily produced the Zip files as part of our data flow and drop the artifacts on the website with a link from the homepage.

**Comment by tmorrell** [comment]
Implemented.  Files available at URLs like https://feeds.library.caltech.edu/CaltechDATA.ds.  Can automate updating local collections using ames (https://github.com/caltechlibrary/ames)
