### ISSUE TITLE
Blank key showing up in feeds for CaltechDATA

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/feeds.library.caltech.edu#20]
Visible via `dataset -c s3://dataset.library.caltech.edu/CaltechDATA keys`

**Comment by tmorrell** [comment]
I manually deleted the record and the blank key was not regenerated in the nightly harvest.  Will note if it happens again

**Comment by rsdoiel** [comment]
I think this was solved and have not been able to reproduce this in pending v0.0.4 release.
