### ISSUE TITLE
Some how eprints "data" key lists are being created when only CaltechDATA "data" lists should be created.

### ISSUE THREAD

**Issue by rsdoiel** [caltechlibrary/feeds.library.caltech.edu#29]
genfeeds.py is creating groups/GROUP_NAME/data.keys from EPrints when it should be creating them from CaltechDATA (being the combined view of CaltechDATA for the present). This causes template errors and empty *.json files in various groups (possibly in person too).

**Comment by tmorrell** [comment]
I think this has been resolved
