### ISSUE TITLE
Investigate odd key values

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/feeds.library.caltech.edu#33]
There seem to be some oddly formatted keys, but I can'd find them in tmp/exported-CaltechTHESIS.keys.  This shows up in the logs at 404 calls to incorrect URLS.  There are just two per repository, possibly the first and last values?  Not a big deal.

2019/03/07 08:33:15 (pid: 47042) Failed, 404 Not Found for https://thesis.library.caltech.edu/rest/eprint/%2211416.xml
2019/03/07 08:33:17 (pid: 47042) Failed, 404 Not Found for https://thesis.library.caltech.edu/rest/eprint/1071%22.xml
2019/03/07 08:37:37 (pid: 47061) Failed, 404 Not Found for https://authors.library.caltech.edu/rest/eprint/%2293611.xml
2019/03/07 08:38:33 (pid: 47061) Failed, 404 Not Found for https://authors.library.caltech.edu/rest/eprint/2732%22.xml

**Comment by rsdoiel** [comment]
I think fixing some of the foundation tooling may have fixed this. I've tested both current production and my development snapshot and no longer can find error. Here's the python code I used to test both the Dataset collections as well as the tmp/*.keys files.

```python
#!/usr/bin/env python3

import dataset
import sys

#print(f'DEBUG sys.argv -> {sys.argv}')
if len(sys.argv) <= 1:
    print(f"test_funny_keys.py DATASET_NAME [DATASET_NAME ...]")

for c_name in sys.argv:
    if c_name.endswith('.keys'):
        with open(c_name) as f:
            src = f.read()
            for line_no, line in enumerate(src.split('\n')):
                if line != '':
                    t_line = line.strip()
                    if line != t_line:
                        print(f'ERROR: {c_name} has odd keys at line {line_no} -> {line} != {t_line}')
        print(f'{c_name} OK')        
    else:
        print(f"Testing dataset keys in {c_name}")
        keys = dataset.keys(c_name)
        for key in keys:
            t_key = key.strip()
            if key != t_key:
                print(f'ERROR: {c_name} odd keys "{key}" != "{t_key}"')
                exit(0)
        print(f'{c_name} OK')        
print(f'All OK, test completed for {", ".join(sys.argv[1:])}')
```

**Comment by rsdoiel** [comment]
Still see a key in thesis harvest on my Mac as %20%20.xml.  The code on my Mac wasn't as current as my laptop. Checking to see where the issue is.

**Comment by rsdoiel** [comment]
Seems wrapping quotes crept into the key lists. I have added defensive code to harvest/harvest.go in eprinttools to solve this issue there.
