### ISSUE TITLE
BibTex improvements

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/feeds.library.caltech.edu#44]
Change publisher to journal
Preprints should have @article type, technical reports should probably have @techreport, others @misc

**Comment by tmorrell** [comment]
@rsdoiel Could you review https://github.com/caltechlibrary/feeds.library.caltech.edu/commit/092260695c4693ee2e50b32726c808103f2ceaf3 and deploy?  I was going to do a PR for this, but accidentally pushed to master.

**Comment by rsdoiel** [comment]
Updated production, confirmed BibTeX generated using htdocs/groups/IQIM/combined.json and running mkpage at the command line. Changes should show up tomorrow.
